export const WORDS = [
  { term: "specimen", ru: "образец" },
  { term: "fossil", ru: "ископаемое; окаменелость" },
  { term: "granted", ru: "допуская; допустим" },
  { term: "coast", ru: "побережье" },
  { term: "introduction", ru: "введение" },
  { term: "postage", ru: "почтовая оплата" },
  { term: "stamp", ru: "марка" },
  { term: "promptly", ru: "быстро; сразу" },
  { term: "arduous", ru: "трудный; изнурительный" },
  { term: "heaps", ru: "кучи" },
  { term: "undeliverable", ru: "недоставляемый" },
  { term: "mail", ru: "почта" },
  { term: "regardless", ru: "несмотря на; независимо от" },
  { term: "on the contrary", ru: "наоборот" },
  { term: "potter", ru: "гончар" },
  { term: "clay", ru: "глина" },
  { term: "desired", ru: "желанный" },
  { term: "intended", ru: "запланированный; предназначенный" },
  { term: "earthenware", ru: "керамика; глиняная посуда" },
  { term: "rustic", ru: "деревенский; простой" },
  { term: "durable", ru: "прочный; долговечный" },
  { term: "flipping", ru: "переворачивание; переворачивать" },
  { term: "yield", ru: "приносить (результат); давать" },
  { term: "hull", ru: "корпус (корабля); оболочка" },
  { term: "tribe", ru: "племя" },
  { term: "ashore", ru: "на берегу" },
  { term: "vibrant", ru: "яркий; насыщенный" },
  { term: "voyage", ru: "путешествие; плавание" },

  { term: "bitingly", ru: "язвительно; резко" },
  { term: "dexterous", ru: "ловкий; умелый" },
  { term: "fittingly", ru: "уместно; подходяще" },
  { term: "inverted", ru: "перевернутый; обратный" },

  { term: "amiable", ru: "дружелюбный; приятный" },
  { term: "amicable", ru: "дружеский; миролюбивый" },
  { term: "impartial", ru: "беспристрастный" },
  { term: "analogous", ru: "аналогичный" },
  { term: "anathema", ru: "анафема; нечто ненавистное" },
  { term: "intransigent", ru: "неуступчивый; непримиримый" },
  { term: "benevolent", ru: "великодушный; доброжелательный" },
  { term: "capricious", ru: "капризный; непредсказуемый" },
  { term: "dubious", ru: "сомнительный" },
  { term: "ephemeral", ru: "мимолетный; недолговечный" },
  { term: "exacerbate", ru: "усугублять" },
  { term: "fastidious", ru: "привередливый; щепетильный" },
  { term: "mendacious", ru: "лживый" },
  { term: "obfuscate", ru: "запутывать; затемнять смысл" },
  { term: "pragmatic", ru: "прагматичный; практичный" },
  { term: "ubiquitous", ru: "повсеместный; вездесущий" },
  { term: "venerate", ru: "почитать" },

  { term: "ambiguous", ru: "двусмысленный; неясный" },
  { term: "apathetic", ru: "апатичный; безразличный" },
  { term: "absurd", ru: "нелепый; абсурдный" },
  { term: "abrupt", ru: "резкий; внезапный" },
  { term: "arrogant", ru: "высокомерный" },
  { term: "complacent", ru: "самодовольный" },
  { term: "condescending", ru: "снисходительный (с высока)" },
  { term: "contentious", ru: "спорный; конфликтный" },
  { term: "cynical", ru: "циничный" },
  { term: "persevere", ru: "упорствовать; не сдаваться" },

  { term: "rekindle", ru: "возродить; разжечь снова" },
  { term: "blackout", ru: "отключение электричества; затемнение" },
  { term: "features", ru: "черты; особенности" },
  { term: "thoroughness", ru: "тщательность" },
  { term: "investigation", ru: "расследование" },
  { term: "executives", ru: "руководители" },
  { term: "internal", ru: "внутренний" },
  { term: "internship", ru: "стажировка" },
  { term: "examined", ru: "изучил; осмотрел" },
  { term: "hence", ru: "следовательно" },
  { term: "specify", ru: "уточнять; конкретизировать" },
  { term: "rope", ru: "веревка" },
  { term: "playfully", ru: "игриво" },
  { term: "cone", ru: "конус" },
  { term: "sloping", ru: "наклонный" },
  { term: "appear", ru: "казаться; появляться" },
  { term: "smooth", ru: "гладкий" },
  { term: "narrative", ru: "повествование" },
  { term: "depiction", ru: "изображение; описание" },
  { term: "blended", ru: "смешанный" },
  { term: "abolished", ru: "отмененный; упраздненный" },
  { term: "ties", ru: "связи" },
  { term: "distinct", ru: "четкий; отдельный" },
  { term: "verse", ru: "стих; строфа" },
  { term: "incorporate", ru: "включать; объединять" },
  { term: "pure", ru: "чистый" },

  { term: "await", ru: "ожидать" },
  { term: "upon", ru: "сразу после; по прибытии" },
  { term: "compound", ru: "составной; сложный" },
  { term: "crisp", ru: "четкий; хрустящий" },
  { term: "conveyed", ru: "передал; донес (мысль)" },
  { term: "plot", ru: "сюжет" },
  { term: "prior", ru: "предыдущий" },
  { term: "abstain", ru: "воздерживаться" },
  { term: "acumen", ru: "проницательность; деловая хватка" },
  { term: "adversity", ru: "трудности; несчастье" },
  { term: "affinity", ru: "сходство; влечение" },
  { term: "alleviate", ru: "облегчать" },
  { term: "ameliorate", ru: "улучшать" },
  { term: "arbitrary", ru: "произвольный" },
  { term: "assert", ru: "утверждать" },
  { term: "audacious", ru: "дерзкий" },
  { term: "buttress", ru: "поддерживать; подкреплять" },
  { term: "candid", ru: "откровенный" },
  { term: "censure", ru: "осуждать" },
  { term: "circumspection", ru: "осторожность" },
  { term: "concede", ru: "признавать; уступать" },
  { term: "copious", ru: "обильный" },
  { term: "cryptic", ru: "загадочный" },
  { term: "dearth", ru: "нехватка" },
  { term: "divergent", ru: "расходящийся; различающийся" },
  { term: "epitome", ru: "олицетворение; воплощение" },
  { term: "evoke", ru: "вызывать (чувства/образы)" },

  { term: "CE", ru: "н. э. (наша эра)" },
  { term: "BCE", ru: "до н. э." },
  { term: "overlapping", ru: "перекрывающийся; пересекающийся" },
  { term: "temporality", ru: "временность" },
  { term: "contemplate", ru: "размышлять; созерцать" },
  { term: "effect", ru: "эффект; влияние" },
  { term: "penchant", ru: "склонность" },
  { term: "adherent", ru: "сторонник; приверженец" },
  { term: "advocate", ru: "выступать в защиту; сторонник" },
  { term: "anachronism", ru: "анахронизм" },
  { term: "anecdote", ru: "короткий рассказ; анекдот" },
  { term: "antithesis", ru: "антитеза; противоположность" },
  { term: "assertion", ru: "утверждение; заявление" },
  { term: "assumption", ru: "предположение" },
  { term: "attribute", ru: "приписывать; свойство" },
  { term: "augment", ru: "увеличивать; дополнять" },
  { term: "conjecture", ru: "догадка; предположение" },
  { term: "corroborate", ru: "подтверждать" },
  { term: "derive", ru: "происходить; получать" },
  { term: "empirical", ru: "эмпирический; основанный на опыте" },
  { term: "imply", ru: "подразумевать; намекать" },
  { term: "inherent", ru: "присущий" },
  { term: "objective", ru: "объективный" },
  { term: "plausible", ru: "правдоподобный" },
  { term: "aloof", ru: "отстраненный" },
  { term: "altruistic", ru: "альтруистический" },

  { term: "idiosyncratic", ru: "своеобразный" },
  { term: "impeded", ru: "затрудненный; с препятствиями" },
  { term: "meticulous", ru: "тщательный; щепетильный" },
  { term: "obscure", ru: "неясный; малоизвестный" },
  { term: "pervasive", ru: "распространенный; пронизывающий" },
  { term: "quintessential", ru: "самый типичный; квинтэссенция" },
  { term: "refute", ru: "опровергать" },
  { term: "skeptical", ru: "скептический" },
  { term: "substantiate", ru: "обосновывать; подтверждать" },
  { term: "tenuous", ru: "слабый; неубедительный; хрупкий" },
  { term: "undermine", ru: "подрывать" },
  { term: "vindicate", ru: "оправдывать; подтверждать правоту" },

  { term: "in particular", ru: "в частности" },
  { term: "specifically", ru: "конкретно" },
  { term: "meanwhile", ru: "тем временем" },
  { term: "still", ru: "тем не менее" },
  { term: "admittedly", ru: "по правде; признаться" },
  { term: "likewise", ru: "так же; аналогично" },
  { term: "indeed", ru: "в самом деле" },

  { term: "champion", ru: "защищать; отстаивать" },
  { term: "insist", ru: "настаивать" },
  { term: "legislation", ru: "законодательство" },
  { term: "fictional", ru: "вымышленный" },
  { term: "remain", ru: "оставаться" },
  { term: "challenged", ru: "оспариваемый; столкнувшийся с трудностью" },

  { term: "as soon as", ru: "как только" }
];
